import ActivityUtils from '../src/ActivityUtils';
import AppUtils from '../src/AppUtils';
import BrightnessUtils from '../src/BrightnessUtils';
import FlashlightUtils from '../src/FlashlightUtils';
import KeyboardUtils from '../src/KeyboardUtils';
import PathUtils from '../src/PathUtils';
import RomUtils from '../src/RomUtils';
import ScreenUtils from '../src/ScreenUtils';
import ServiceUtils from '../src/ServiceUtils';
import ShellUtils from '../src/ShellUtils';
import VibrateUtils from '../src/VibrateUtils';
import VolumeUtils from '../src/VolumeUtils';
import ZipUtils from '../src/ZipUtils';
import AppStoreUtils from '../src/AppStoreUtils';
import IntentLauncherUtils from '../src/IntentLauncherUtils';

export type IntentConstant =  {
  ATTR_ACTION: string,
  TAG_CATEGORIES: string,
  ATTR_CATEGORY: string,
  TAG_EXTRA: string,
  ATTR_TYPE: string,
  ATTR_COMPONENT: string,
  ATTR_DATA: string,
  ATTR_FLAGS: string,
  ACTION_MAIN: string,
  ACTION_VIEW: string,
  ACTION_DEFAULT: string;
  ACTION_ATTACH_DATA: string,
  ACTION_EDIT: string,
  ACTION_INSERT_OR_EDIT: string,
  ACTION_PICK: string,
  ACTION_CREATE_SHORTCUT: string,
  EXTRA_SHORTCUT_INTENT: string,
  EXTRA_SHORTCUT_NAME: string,
  EXTRA_SHORTCUT_ICON: string,
  ACTION_CHOOSER: string,
  ACTION_GET_CONTENT: string,
  ACTION_DIAL: string,
  ACTION_CALL: string,
  ACTION_CALL_EMERGENCY: string,
  ACTION_CALL_PRIVILEGED: string,
  ACTION_SENDTO: string,
  ACTION_SEND: string,
  ACTION_SEND_MULTIPLE: string,
  ACTION_ANSWER: string,
  ACTION_INSERT: string,
  ACTION_PASTE: string,
  ACTION_DELETE: string,
  ACTION_RUN: string,
  ACTION_SYNC: string,
  ACTION_PICK_ACTIVITY: string,
  ACTION_SEARCH: string,
  ACTION_SYSTEM_TUTORIAL: string,
  ACTION_WEB_SEARCH: string,
  ACTION_ASSIST: string,
  ACTION_VOICE_ASSIST: string,
  ACTION_ALL_APPS: string,
  ACTION_SET_WALLPAPER: string,
  ACTION_BUG_REPORT: string,
  ACTION_FACTORY_TEST: string,
  ACTION_CALL_BUTTON: string,
  ACTION_VOICE_COMMAND: string,
  ACTION_SEARCH_LONG_PRESS: string,
  ACTION_APP_ERROR: string,
  ACTION_POWER_USAGE_SUMMARY: string,
  ACTION_UPGRADE_SETUP: string,
  ACTION_INSTALL_PACKAGE: string,
  ACTION_UNINSTALL_PACKAGE: string,
  METADATA_SETUP_VERSION: string,
  EXTRA_PACKAGE_NAME: string,
  EXTRA_PERMISSION_NAME: string,
  ACTION_SCREEN_OFF: string,
  ACTION_SCREEN_ON: string,
  ACTION_DREAMING_STOPPED: string,
  ACTION_DREAMING_STARTED: string,
  ACTION_USER_PRESENT: string,
  ACTION_TIME_TICK: string,
  ACTION_TIME_CHANGED: string,
  ACTION_DATE_CHANGED: string,
  ACTION_TIMEZONE_CHANGED: string,
  ACTION_CLEAR_DNS_CACHE: string,
  ACTION_ALARM_CHANGED: string,
  ACTION_BOOT_COMPLETED: string,
  ACTION_CLOSE_SYSTEM_DIALOGS: string,
  ACTION_PACKAGE_INSTALL: string,
  ACTION_PACKAGE_ADDED: string,
  ACTION_PACKAGE_REPLACED: string,
  ACTION_MY_PACKAGE_REPLACED: string,
  ACTION_PACKAGE_REMOVED: string,
  ACTION_PACKAGE_CHANGED: string,
  ACTION_QUERY_PACKAGE_RESTART: string,
  ACTION_PACKAGE_RESTARTED: string,
  ACTION_PACKAGE_DATA_CLEARED: string,
  ACTION_UID_REMOVED: string,
  ACTION_PACKAGE_FIRST_LAUNCH: string,
  ACTION_PACKAGE_NEEDS_VERIFICATION: string,
  ACTION_PACKAGE_VERIFIED: string,
  ACTION_INTENT_FILTER_NEEDS_VERIFICATION: string,
  ACTION_WALLPAPER_CHANGED: string,
  ACTION_CONFIGURATION_CHANGED: string,
  ACTION_LOCALE_CHANGED: string,
  ACTION_BATTERY_CHANGED: string,
  ACTION_BATTERY_LOW: string,
  ACTION_BATTERY_OKAY: string,
  ACTION_POWER_CONNECTED: string,
  ACTION_SHUTDOWN: string,
  ACTION_REQUEST_SHUTDOWN: string,
  ACTION_DEVICE_STORAGE_LOW: string,
  ACTION_DEVICE_STORAGE_OK: string,
  ACTION_DEVICE_STORAGE_FULL: string,
  ACTION_DEVICE_STORAGE_NOT_FULL: string,
  ACTION_MANAGE_PACKAGE_STORAGE: string,
  ACTION_UMS_CONNECTED: string,
  ACTION_UMS_DISCONNECTED: string,
  ACTION_MEDIA_REMOVED: string,
  ACTION_MEDIA_UNMOUNTED: string,
  ACTION_MEDIA_CHECKING: string,
  ACTION_MEDIA_NOFS: string,
  ACTION_MEDIA_MOUNTED: string,
  ACTION_MEDIA_SHARED: string,
  ACTION_MEDIA_UNSHARED: string,
  ACTION_MEDIA_BAD_REMOVAL: string,
  ACTION_MEDIA_UNMOUNTABLE: string,
  ACTION_MEDIA_EJECT: string,
  ACTION_MEDIA_SCANNER_STARTED: string,
  ACTION_MEDIA_SCANNER_FINISHED: string,
  ACTION_MEDIA_SCANNER_SCAN_FILE: string,
  ACTION_MEDIA_BUTTON: string,
  ACTION_CAMERA_BUTTON: string,
  ACTION_AIRPLANE_MODE_CHANGED: string,
  ACTION_GLOBAL_BUTTON: string,
  ACTION_OPEN_DOCUMENT: string,
  ACTION_CREATE_DOCUMENT: string,
  ACTION_MASTER_CLEAR: string,
  ACTION_SETTING_RESTORED: string,
  EXTRA_SETTING_NAME: string,
  EXTRA_SETTING_PREVIOUS_VALUE: string,
  EXTRA_SETTING_NEW_VALUE: string,
  ACTION_PROCESS_TEXT: string,
  EXTRA_PROCESS_TEXT: string,
  ACTION_THERMAL_EVENT: string,
  EXTRA_THERMAL_STATE: string,
  EXTRA_THERMAL_STATE_NORMAL: number,
  EXTRA_THERMAL_STATE_WARNING: number,
  EXTRA_THERMAL_STATE_EXCEEDED: number,
  CATEGORY_DEFAULT: string,
  CATEGORY_BROWSABLE: string,
  CATEGORY_VOICE: string,
  CATEGORY_ALTERNATIVE: string,
  CATEGORY_SELECTED_ALTERNATIVE: string,
  CATEGORY_TAB: string,
  CATEGORY_LAUNCHER: string,
  CATEGORY_LEANBACK_LAUNCHER: string,
  CATEGORY_LEANBACK_SETTINGS: string,
  CATEGORY_INFO: string,
  CATEGORY_HOME: string,
  CATEGORY_HOME_MAIN: string,
  CATEGORY_SETUP_WIZARD: string,
  CATEGORY_PREFERENCE: string,
  CATEGORY_DEVELOPMENT_PREFERENCE: string,
  CATEGORY_EMBED: string,
  CATEGORY_APP_MARKET: string,
  CATEGORY_MONKEY: string,
  CATEGORY_TEST: string,
  CATEGORY_UNIT_TEST: string,
  CATEGORY_SAMPLE_CODE: string,
  CATEGORY_OPENABLE: string,
  CATEGORY_CAR_DOCK: string,
  CATEGORY_DESK_DOCK: string,
  CATEGORY_LE_DESK_DOCK: string,
  CATEGORY_HE_DESK_DOCK: string,
  CATEGORY_CAR_MODE: string,
  CATEGORY_APP_BROWSER: string,
  CATEGORY_APP_CALCULATOR: string,
  CATEGORY_APP_CALENDAR: string,
  CATEGORY_APP_CONTACTS: string,
  CATEGORY_APP_EMAIL: string,
  CATEGORY_APP_GALLERY: string,
  CATEGORY_APP_MAPS: string,
  CATEGORY_APP_MESSAGING: string,
  CATEGORY_APP_MUSIC: string,
  EXTRA_TEMPLATE: string,
  EXTRA_TEXT: string,
  EXTRA_HTML_TEXT: string,
  EXTRA_STREAM: string,
  EXTRA_INTENT: string,
  EXTRA_ALTERNATE_INTENTS: string,
  EXTRA_TITLE: string,
  EXTRA_INITIAL_INTENTS: string,
  EXTRA_CHOSEN_COMPONENT: string,
  EXTRA_KEY_EVENT: string,
  EXTRA_KEY_CONFIRM: string,
  EXTRA_DONT_KILL_APP: string,
  EXTRA_PHONE_NUMBER: string,
  EXTRA_UID: string,
  EXTRA_PACKAGES: string,
  EXTRA_DATA_REMOVED: string,
  EXTRA_REPLACING: string,
  EXTRA_ALARM_COUNT: string,
  EXTRA_DOCK_STATE: string,
  EXTRA_DOCK_STATE_UNDOCKED: number,
  EXTRA_DOCK_STATE_DESK: number,
  EXTRA_DOCK_STATE_CAR: number,
  EXTRA_DOCK_STATE_LE_DESK: number,
  EXTRA_DOCK_STATE_HE_DESK: number,
  METADATA_DOCK_HOME: string,
  EXTRA_BUG_REPORT: string,
  EXTRA_RESTRICTIONS_LIST: string,
  EXTRA_MIME_TYPES: string,
  EXTRA_REASON: string,
  EXTRA_WIPE_EXTERNAL_STORAGE: string,
  FLAG_GRANT_READ_URI_PERMISSION: number,
  FLAG_GRANT_WRITE_URI_PERMISSION: number,
  FLAG_FROM_BACKGROUND: number,
  FLAG_DEBUG_LOG_RESOLUTION: number,
  FLAG_EXCLUDE_STOPPED_PACKAGES: number,
  FLAG_INCLUDE_STOPPED_PACKAGES: number,
  FLAG_GRANT_PERSISTABLE_URI_PERMISSION: number,
  FLAG_GRANT_PREFIX_URI_PERMISSION: number,
  FLAG_ACTIVITY_NO_HISTORY: number,
  FLAG_ACTIVITY_SINGLE_TOP: number,
  FLAG_ACTIVITY_NEW_TASK: number,
  FLAG_ACTIVITY_MULTIPLE_TASK: number,
  FLAG_ACTIVITY_CLEAR_TOP: number,
  FLAG_ACTIVITY_FORWARD_RESULT: number,
  FLAG_ACTIVITY_PREVIOUS_IS_TOP: number,
  FLAG_ACTIVITY_EXCLUDE_FROM_RECENTS: number,
  FLAG_ACTIVITY_BROUGHT_TO_FRONT: number,
  FLAG_ACTIVITY_RESET_TASK_IF_NEEDED: number,
  FLAG_ACTIVITY_LAUNCHED_FROM_HISTORY: number,
  FLAG_ACTIVITY_CLEAR_WHEN_TASK_RESET: number,
  FLAG_ACTIVITY_NEW_DOCUMENT: number,
  FLAG_ACTIVITY_NO_USER_ACTION: number,
  FLAG_ACTIVITY_REORDER_TO_FRONT: number,
  FLAG_ACTIVITY_NO_ANIMATION: number,
  FLAG_ACTIVITY_CLEAR_TASK: number,
  FLAG_ACTIVITY_TASK_ON_HOME: number,
  FLAG_ACTIVITY_RETAIN_IN_RECENTS: number,
  FLAG_RECEIVER_REGISTERED_ONLY: number,
  FLAG_RECEIVER_REPLACE_PENDING: number,
  FLAG_RECEIVER_FOREGROUND: number,
  FLAG_RECEIVER_NO_ABORT: number,
  FLAG_RECEIVER_REGISTERED_ONLY_BEFORE_BOOT: number,
  FLAG_RECEIVER_BOOT_UPGRADE: number,
  URI_INTENT_SCHEME: number,
  URI_ANDROID_APP_SCHEME: number,
  URI_ALLOW_UNSAFE: number,
  FILL_IN_ACTION: number,
  FILL_IN_DATA: number,
  FILL_IN_CATEGORIES: number,
  FILL_IN_COMPONENT: number,
  FILL_IN_PACKAGE: number,
  FILL_IN_SOURCE_BOUNDS: number,
  FILL_IN_SELECTOR: number,
  FILL_IN_CLIP_DATA: number,
}

export type appInfo = {
  name: string;
  packageName: string;
  packagePath: string;
  versionName: string;
  versionCode: number;
  isSystem: number;
}

export type resolveInfo = {
  icon: number;
  isDefault: boolean;
  isInstantAppAvailable: boolean;
  labelRes: number;
  match: number;
  preferredOrder: number;
  priority: number;
  resolvePackageName: string;
  activityInfo: {
    banner: number;
    icon: number;
    labelRes: number;
    logo: number;
    name: string;
    packageName: string;
    metaData: Record<string, any>;
  }
}

export type intent = {
  action: string,
  category: string,
  flags?:number,
  data:string,
  type?:string,
  extra?:string,
  packageName?:string,
  classPackageName?:string,
  className?:string
}


export const IntentConstant: IntentConstant;

export {
  ActivityUtils,
  AppUtils,
  BrightnessUtils,
  FlashlightUtils,
  KeyboardUtils,
  PathUtils,
  RomUtils,
  ScreenUtils,
  ServiceUtils,
  ShellUtils,
  VibrateUtils,
  VolumeUtils,
  ZipUtils,
  AppStoreUtils,
  IntentLauncherUtils
}

export default IntentLauncherUtils;
